<?xml version="1.0" encoding="utf-8"?><Database Name="Base" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Base.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="ZpProject.Properties.Settings" SettingsPropertyName="BaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PaymentTypes" Member="PaymentTypes">
    <Type Name="PaymentType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsIncrement" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="PaymentType_Payment" Member="Payments" ThisKey="ID" OtherKey="PaymentTypeID" Type="Payment" />
    </Type>
  </Table>
  <Table Name="dbo.Departments" Member="Departments">
    <Type Name="Department">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="ID" OtherKey="DepartmentID" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FIO" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Employee_PaymentEmployee" Member="PaymentEmployees" ThisKey="ID" OtherKey="EmployeeID" Type="PaymentEmployee" />
      <Association Name="Department_Employee" Member="Department" ThisKey="DepartmentID" OtherKey="ID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentEmployees" Member="PaymentEmployees">
    <Type Name="PaymentEmployee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaymentPeriodID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PaymentEmployee_Payment" Member="Payments" ThisKey="ID" OtherKey="PaymentEmployeeID" Type="Payment" />
      <Association Name="Employee_PaymentEmployee" Member="Employee" ThisKey="EmployeeID" OtherKey="ID" Type="Employee" IsForeignKey="true" />
      <Association Name="PaymentPeriod_PaymentEmployee" Member="PaymentPeriod" ThisKey="PaymentPeriodID" OtherKey="ID" Type="PaymentPeriod" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentPeriods" Member="PaymentPeriods">
    <Type Name="PaymentPeriod">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Year" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Month" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="PaymentPeriod_PaymentEmployee" Member="PaymentEmployees" ThisKey="ID" OtherKey="PaymentPeriodID" Type="PaymentEmployee" />
    </Type>
  </Table>
  <Table Name="dbo.Payments" Member="Payments">
    <Type Name="Payment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaymentEmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="PaymentEmployee_Payment" Member="PaymentEmployee" ThisKey="PaymentEmployeeID" OtherKey="ID" Type="PaymentEmployee" IsForeignKey="true" />
      <Association Name="PaymentType_Payment" Member="PaymentType" ThisKey="PaymentTypeID" OtherKey="ID" Type="PaymentType" IsForeignKey="true" />
    </Type>
  </Table>
</Database>